from django.db import models

# Create your models here.
class Signup(models.Model):
    name=models.CharField(max_length=10,null=False,blank=False,default="")
    father_name=models.CharField(max_length=20,null=False,blank=False,default="")
    phone_number=models.CharField(max_length=11,null=False,blank=False)
    email_address=models.EmailField(max_length=20,null=False,blank=False,default="")
    password=models.CharField(max_length=20,null=False,blank=False,default="")
    cnic=models.CharField(max_length=15,null=False,primary_key=True)
class Admission(models.Model):
    date=models.DateField(auto_now_add=True,null=True,blank=True)
    name=models.CharField(max_length=10,null=False) 
    father_name=models.CharField(max_length=20,null=False)
    father_occupation=models.CharField(max_length=10,null=True)
    phone_number=models.CharField(max_length=20,null=False)
    email_address=models.EmailField(max_length=20,null=False)
    password=models.CharField(max_length=20,null=False)
    matric_school_name=models.TextField(max_length=30,null=False)
    matric_marks=models.CharField(max_length=10,null=False)
    matric_roll_number=models.CharField(max_length=10,null=False)
    matric_board=models.CharField(max_length=20)
    inter_college_name=models.CharField(max_length=40,null=False)
    inter_marks=models.CharField(max_length=20)
    inter_roll_number=models.CharField(max_length=20)
    department=models.CharField(max_length=20)
    image=models.ImageField(upload_to='admissions')
    Gender=models.CharField(max_length=20,blank=False)

class User_login(models.Model):
    name=models.CharField(max_length=10)
    email_address=models.EmailField(max_length=20)
    password=models.CharField(max_length=20)
    cnic=models.CharField(max_length=20)
class Admin(models.Model):
    name=models.CharField(max_length=10)
    first_name=models.CharField(max_length=10)
    last_name=models.CharField(max_length=10) 
    password=models.CharField(max_length=20)   
class Car_parking(models.Model):
    name=models.CharField(max_length=20)
    father_name=models.CharField(max_length=10)
    phone_number=models.CharField(max_length=20)
    registration_number=models.CharField(max_length=20)
    vehicle_number=models.CharField(max_length=20)
    vehicle_type=models.CharField(max_length=20)
    upload_paid_challan_pic=models.ImageField(upload_to='parking')    
class Library(models.Model):
    name=models.CharField(max_length=20)
    father_name=models.CharField(max_length=20)
    registration_number=models.CharField(max_length=20)
    password=models.CharField(max_length=20)
    email=models.EmailField(max_length=30)
    department=models.CharField(max_length=20)
    section=models.CharField(max_length=20)    

class Fee(models.Model):
    date=models.DateField(auto_now_add=True,null=True,blank=True)
    name=models.CharField(max_length=20)
    father_name=models.CharField(max_length=20)
    phone_number=models.CharField(max_length=20)
    registration_number=models.CharField(max_length=20)
    department=models.CharField(max_length=20)
    section=models.CharField(max_length=10)
    email=models.EmailField(max_length=30)
    monthly_income=models.CharField(max_length=20)
    gender=models.CharField(max_length=20)
    fee_challan=models.ImageField(upload_to='fee_concession')
class Repeat_course(models.Model):
    date=models.DateField(auto_now_add=True,null=True,blank=True)
    email=models.EmailField(max_length=40)
    name=models.CharField(max_length=20)
    father_name=models.CharField(max_length=20)
    phone_number=models.CharField(max_length=20)
    department=models.CharField(max_length=20)
    semester=models.CharField(max_length=20)
    section=models.CharField(max_length=20)
    image=models.ImageField(upload_to='Repeat_course')

class Scholarship(models.Model):
    image=models.ImageField(upload_to='scholarship',null=False,blank=False)

class Scholarship_data(models.Model):
    date=models.DateField(auto_now_add=True,null=True,blank=True)
    name=models.CharField(max_length=20)
    father_name=models.CharField(max_length=20)
    phone_number=models.CharField(max_length=50)
    email_address=models.EmailField(max_length=20)
    password=models.CharField(max_length=20)
    roll_number=models.CharField(max_length=20)
    department=models.CharField(max_length=20)
    semester=models.CharField(max_length=20)
    section=models.CharField(max_length=20)
    monthly_income=models.CharField(max_length=20)
    gardian_profession=models.CharField(max_length=20)
    gender=models.CharField(max_length=20)
