from django.urls import path
from myapp import admin
from myapp.views import(
    first_url,
    second_url,
    third_url,
    fourth_url,
    fifth_url,
    car_parking,
    library,
    fee,
    repeat,
    scholarshipsF,
    scholarshipupload,
    apply_scholarship,
    otp_template,
    reverification,
    admin,admission,
    scholarship,
    parking,
    feed,
    library_card,
    repeat_a,
    signup_api
    )

urlpatterns = [
    path('',first_url),
    path('otp/',otp_template),
    path('otp/reverification/',reverification),
    path('otp/signup/',second_url),
    path('otp/signup/Admissions/',third_url),
    path('otp/signup/car_parking/',car_parking),
    path('otp/signup/scholarship/',scholarshipsF),
    path('otp/signup/scholarship/apply_scholarship/',apply_scholarship),
    path('admin_login/Admin/',admin),
    path('admin_login/Admin/admission_data/',admission),
    path('admin_login/Admin/scholarship_data/',scholarship),
    path('admin_login/Admin/fee_concession_data/',feed),
    path('admin_login/Admin/library_card_applicants_data/',library_card),
    path('admin_login/Admin/repeat_course_data/',repeat),
    path('admin_login/Admin/vehicle_parking_data/',parking),
    path('admin_login/Admin/scholarship_upload/',scholarshipupload),
    path('login/',fourth_url),
    path('login/main/',second_url),
    path('login/main/Admissions/',third_url),
    path('login/main/car_parking/',car_parking),
    path('admin_login/',fifth_url),
    path('otp/signup/library_approval/',library),
    path('login/main/library_approval/',library),
    path('login/main/fee_concession/',fee),
    path('otp/signup/fee_concession/',fee),
    path('otp/signup/repeat_course/',repeat_a),
    path('login/main/repeat_course/',repeat_a),
    path('login/main/scholarship/',scholarshipsF),
    path('login/main/scholarship/apply_scholarship/',apply_scholarship),
    # These are api urls 
    path('signup_api/',signup_api)
]
