# Generated by Django 5.0.2 on 2024-05-11 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='id',
        ),
        migrations.AlterField(
            model_name='signup',
            name='cnic',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
